### ISSUE TITLE
migrate osbkit/minibroker to kubernetes-sigs/minibroker

### ISSUE THREAD

**Issue by jberkhahn** [kubernetes/org#894] opened 2019-06-06 19:59 UTC
### New Repo, Staging Repo, or migrate existing
migrate existing github.com/osbkit/minibroker

### Requested name for new repository
minibroker

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
the kubernetes-sigs team `service-catalog-admins`

### If not a staging repo, who should have write access
the kubernetes-sigs team `service-catalog-maintainers`

### If not a staging repo, who should be listed as approvers in OWNERS
the kubernetes-sigs team `service-catalog-maintainers`

### If not a staging repo, who should be listed in SECURITY_CONTACTS
jberkhahn

### What should the repo description be
A minibroker for your minikube! 

### What SIG and subproject does this fall under in sigs.yaml
this is a new subproject for sig-service-catalog called minibroker. Previously it was a personal project maintained by a sevice-catalog contribtuor, carolynvs. We want to use it in
our docs and walkthroughs, and she has graciously decided to donate it to us.

### Approvals
This was discussed in person, it's really up to @carolynvs 

### Additional context for request
Again, talk to @carolynvs

**Comment by carolynvs** [comment] 2019-06-06 20:07
I would love to have it migrate over to the kubernetes-sigs/minibroker, but I'm not sure who to work with on that. @cblecker sorry to drag you in but I hear helped with moving service-catalog. Would you know who I can chat with to do the migration of the repository?

**Comment by nikhita** [comment] 2019-06-07 05:22
:wave: Anyone on the [GitHub admin team](https://github.com/kubernetes/community/tree/master/github-management#github-administration-team) should be able to do it  :)

/assign

> I would love to have it migrate over to the kubernetes-sigs/minibroker

I'll take this as a lgtm :+1:

**Comment by nikhita** [comment] 2019-06-07 06:07
Donated repos need to satisfy some [requirements](https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#rules-for-donated-repositories). As per these requirements, the following steps need to be done before the migration:

- All contributors need to have the CNCF CLA signed. The following contributors do not have the CLA signed:
   - @mook-as 
   - @DanielJonesEB
   - @f0rmiga
 If your name is listed above, could you sign the CNCF CLA so that https://github.com/osbkit/minibroker can be migrated to the Kubernetes project? Instructions for signing the CLA can be found [here](https://github.com/kubernetes/community/blob/master/CLA.md). :)

- The repo needs the following template files - `code-of-conduct.md`, `CONTRIBUTING.md`, `OWNERS`, `SECURITY_CONTACTS` to be incorporated into the Kubernetes project.
@carolynvs or @jberkhahn can either of you add these files to the repo? The template files can be found here - https://github.com/kubernetes/kubernetes-template-project.

- Files in the repo need to have the Kubernetes boilerplate header. Can you also add the boilerplate header to all relevant files?
  - You can find the boilerplate header here for different file extensions here - https://github.com/kubernetes/kubernetes/tree/master/hack/boilerplate
  - If you want to setup a verify script, https://github.com/kubernetes-sigs/cluster-api-provider-digitalocean/pull/111 is an example that does this.
  - To automatically update the header across all files, you can also use https://github.com/kubernetes/repo-infra/pull/82.

- I ran a [FOSSA license scan](https://app.fossa.com/projects/git%2Bgithub.com%2Fnikhita-bot%2Fminibroker/refs/branch/master/c5801cf1cee31aac4db33b2559b63d697677c9ca/preview) for the repo and while a few dependencies were flagged, they are false positives, so all's good there. :+1:

**Comment by nikhita** [comment] 2019-06-07 06:53
Oh also -- @carolynvs, could you add me as an admin to the repo to transfer it? It's okay to do this after all the requirements above have been addressed too. :+1:

**Comment by carolynvs** [comment] 2019-06-07 14:39
Thanks for the guidance, @nikhita! I've made you admin and will start working on the task list this weekend.

**Comment by DanielJonesEB** [comment] 2019-06-07 17:23
@nikhita Thanks for alerting me. I have now signed the CLA.

**Comment by mook-as** [comment] 2019-06-07 17:34
I have attached my GitHub account to my existing LF account (which has signed an employer-wide CLA).

**Comment by nikhita** [comment] 2019-06-08 02:21
@mook-as Thanks, I can confirm that your CLA has been signed.

@DanielJonesEB Thanks for getting to this so quickly! Unfortunately, the bot still says that you don't have the CLA signed. Could you try again or reach out to Linux Foundation at https://github.com/kubernetes/community/blob/master/CLA.md#troubleshooting? Sorry for the trouble! :bowing_woman:

**Comment by DanielJonesEB** [comment] 2019-06-10 06:58
@nikhita I've signed a Corporate CLA for EngineerBetter Ltd. It's definitely signed (I went through the HelloSign process, documents were emailed, and I can see the PDF in the LF portal), and the commit was made with the same email address I used when setting up the LF stuff.

The support suggestion is to open a ticket, but I'm not sure what I should say other than "I think I've signed a CLA but the bot says I haven't".

Any ideas on how I can debug this further?

**Comment by f0rmiga** [comment] 2019-06-10 23:12
@nikhita @carolynvs I've also attached my Github account to the Linux Foundation account. Let me know if everything looks fine. :)

**Comment by nikhita** [comment] 2019-06-11 12:52
@DanielJonesEB @f0rmiga Unfortunately the bot says that the CLA isn't signed for both of you. :disappointed: 

> The support suggestion is to open a ticket, but I'm not sure what I should say other than "I think I've signed a CLA but the bot says I haven't".

Can you open a dummy PR against https://github.com/kubernetes-sigs/contributor-playground? The bot should add a `cncf-cla: yes` label, but if it adds a `cncf-cla: no` label instead, linking that PR to the support ticket should be a little helpful.

Apologies for the back and forth on this, the CLA bot isn't open source yet so opening a ticket is the only way to solve things for now.

**Comment by DanielJonesEB** [comment] 2019-06-11 13:27
Aha - I'd signed the Corporate CLA on behalf of EngineerBetter Ltd, but I needed to [sign up as an employee](https://identity.linuxfoundation.org/projects/cncf/employee-signup) additionally.

**Comment by f0rmiga** [comment] 2019-06-11 17:48
@nikhita Looks like I got it right now. @DanielJonesEB Thanks for pointing it out. :)

**Comment by nikhita** [comment] 2019-06-12 03:47
@DanielJonesEB @f0rmiga yay, thank you so much for following up! :)

@carolynvs please ping me here or on slack once the other tasks are done and I'll migrate the repo. :white_check_mark:

**Comment by carolynvs** [comment] 2019-06-18 13:50
@nikhita I have performed all of the tasks, would you please take a look when you have time and migrate the repository?

**Comment by nikhita** [comment] 2019-06-18 16:13
Migration done: https://github.com/kubernetes-sigs/minibroker :tada: 

Also created https://github.com/kubernetes/community/pull/3813 to update sigs.yaml.

@carolynvs can the netlify webhook be removed? There seems to be no `netlify.toml` as well.

We also have a process around requesting subproject websites if you want to integrate netlify btw: https://github.com/kubernetes/community/blob/master/github-management/subproject-site-requests.md. :)

![Screenshot from 2019-06-18 21-40-37](https://user-images.githubusercontent.com/16105680/59700818-d3fa3400-9211-11e9-8e64-bd922ee458fa.png)

**Comment by carolynvs** [comment] 2019-06-18 17:01
I'll remove the netlify stuff. I was going to use it then didn't end up getting around to hooking up a website (minibroker.sh).

**Comment by nikhita** [comment] 2019-06-18 17:04
@carolynvs :+1: 

Once https://github.com/kubernetes/community/pull/3813 merges, we can close this issue.

**Comment by carolynvs** [comment] 2019-06-18 17:26
Thank you SOOOO MUCH for all of your guidance in getting minibroker migrated over. You did so much and made it really easy for me to donate. ❤️  I really appreciate it and am so excited to see minibroker turned into a subproject! _squeeeee_

**Comment by nikhita** [comment] 2019-06-19 02:43
Webhook removed and https://github.com/kubernetes/community/pull/3813 merged.

/close

**Closed by nikhita** 2019-06-19 02:43 UTC
Labels: area/github-repo
