### ISSUE TITLE
REQUEST: New membership for seifrajhi

### ISSUE THREAD

**Issue by seifrajhi** [kubernetes/org#4827] opened 2024-03-15 07:49 UTC
### GitHub Username

seifrajhi

### Organization you are requesting membership in

kubernetes, kubernetes-sigs

### Requirements

- [X] I have reviewed the [community membership guidelines](https://git.k8s.io/community/community-membership.md)
- [X] I have [enabled 2FA on my GitHub account](https://github.com/settings/security)
- [X] I have subscribed to the [kubernetes dev e-mail list](https://groups.google.com/a/kubernetes.io/group/dev)
- [X] I am actively contributing to 1 or more Kubernetes subprojects
- [X] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [X] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application
- [X] I have verified that my sponsors are from different member companies
- [X] I have verified that my sponsors are a reviewer or an approver in at least one OWNERS file within one of the Kubernetes GitHub organizations (excluding the contributor-playground)
- [x] **OPTIONAL:** I have taken the [Inclusive Open Source Community Orientation course](https://training.linuxfoundation.org/training/inclusive-open-source-community-orientation-lfc102/)
   
  - [Credly badge](https://www.credly.com/badges/f61adfbf-5118-45a2-b072-9bc6e5338c20) for the LFC102: Inclusive Open Source Community Orientation
### Sponsor 1

shurup

### Sponsor 2

mboukhalfa

### List of contributions to the Kubernetes project

Issues:

- https://github.com/kubernetes/website/issues/45482
- https://github.com/kubernetes/website/issues/45331
- https://github.com/kubernetes/website/issues/45327

PRs

Authored:

- https://github.com/kubernetes/website/pull/45357
- https://github.com/kubernetes/website/pull/45338
- https://github.com/kubernetes/website/pull/45336
- https://github.com/kubernetes/website/pull/45332
- https://github.com/kubernetes/website/pull/45330
- https://github.com/kubernetes/website/pull/45328
- https://github.com/kubernetes/website/pull/45326
- https://github.com/kubernetes/website/pull/45047
- https://github.com/kubernetes/website/pull/44031
- https://github.com/kubernetes-sigs/krew-index/pull/3157
- https://github.com/kubernetes/website/pull/45326

Reviewed:

- https://github.com/kubernetes/website/pull/45082
- https://github.com/kubernetes/website/pull/45065
- https://github.com/kubernetes/website/pull/45064
- https://github.com/kubernetes/website/pull/45056
- https://github.com/kubernetes/website/pull/44698

**Comment by shurup** [comment] 2024-03-15 08:58
+1

**Comment by mboukhalfa** [comment] 2024-03-15 14:44
+1
Welcome :)

**Comment by jasonbraganza** [comment] 2024-03-16 03:34
@mboukhalfa would you kindly update your profile with your place of work? or please provide it here on this issue?
We need it because, according to our [membership guidlines](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements) sponsors need to be from different orgs.

**Comment by mboukhalfa** [comment] 2024-03-16 15:50
> @mboukhalfa would you kindly update your profile with your place of work? or please provide it here on this issue? We need it because, according to our [membership guidlines](https://github.com/kubernetes/community/blob/master/community-membership.md#requirements) sponsors need to be from different orgs.

@jasonbraganza I am not planning to set that on my github however I can confirm from a different different org! Else I guess @seifrajhi can find more sponsors

**Comment by mrbobbytables** [comment] 2024-04-03 23:14
Thank you for all your contributions so far :)

I've created PR #4869  to add you to org(s). Once that gets merged, you should get a membership invite notification.

Welcome aboard! :D

**Closed** 2024-04-09 03:47 UTC
Labels: area/github-membership

**Comment by seifrajhi** [comment] 2024-04-09 06:45
Hello @mrbobbytables,

Thank you very much for the effor :) I am able to join `kubernetes` org 🎉 

However. I have not yet received an invitation to the `kubernetes-sigs`. Is that ok, it might take longer ?

**Comment by jasonbraganza** [comment] 2024-04-09 07:06
@seifrajhi Yes, please it a while. a day at least.
