### ISSUE TITLE
Migrate DirectXMan12/k8s-prometheus-adapter to kubernetes-sigs

### ISSUE THREAD

**Issue by brancz** [kubernetes/org#2182] opened 2020-09-10 13:32 UTC
### New Repo, Staging Repo, or migrate existing
Migrate DirectXMan12/k8s-prometheus-adapter to kubernetes-sigs

### Requested name for new repository
prometheus-adapter

### Which Organization should it reside
kubernetes-sigs

### If not a staging repo, who should have admin access
@DirectXMan12 , @s-urbaniak , myself ( @brancz )

### If not a staging repo, who should have write access
@DirectXMan12 , @s-urbaniak , myself ( @brancz )

### If not a staging repo, who should be listed as approvers in OWNERS
@DirectXMan12 , @s-urbaniak , myself ( @brancz )

### If not a staging repo, who should be listed in SECURITY_CONTACTS
@DirectXMan12 , @s-urbaniak , myself ( @brancz )

### What should the repo description be

```
An implementation of the custom.metrics.k8s.io API using Prometheus.
```

### What SIG and subproject does this fall under in sigs.yaml
this is a new subproject for sig-instrumentation

### Approvals

Following the [SIG instrumentation charter](https://github.com/kubernetes/community/blob/master/sig-instrumentation/charter.md) there was a [the public thread on the donation proposal](https://groups.google.com/g/kubernetes-sig-instrumentation/c/xnD9xxVEab0/m/4b-aVdEHAAAJ), which was accepted through lazy consensus. Additionally, this topic was brought up in the [2020-08-06 and 2020-07-09 SIG meetings](https://docs.google.com/document/d/1FE4AQ8B49fYbKhfg4Tx0cui1V0eI4o3PxoqQPUwNEiU/edit#heading=h.qpfxt91hdl2x), without objection.

@DirectXMan12 @kubernetes/sig-instrumentation-misc 

cc @nikhita

**Comment by DirectXMan12** [comment] 2020-09-11 21:46
Hey, so we probably just want me to transfer the repository, right?  It'll keep issues and such.

**Comment by DirectXMan12** [comment] 2020-09-11 21:47
I can give one of the GH admins permission on the repo so that they can do the transfer.  Let me know.

**Comment by DirectXMan12** [comment] 2020-09-11 21:48
(can't do it myself apparently, since I don't have permission to create repos in k-sigs)

**Comment by brancz** [comment] 2020-09-14 05:35
> Hey, so we probably just want me to transfer the repository, right? It'll keep issues and such.

Yep :)

> I can give one of the GH admins permission on the repo so that they can do the transfer. Let me know.

I imagine that could speed things up.

cc @mrbobbytables

**Comment by nikhita** [comment] 2020-09-14 07:36
Unfortunately, we'll need to do a few more things before migration :( 

- Template files like code-of-conduct, etc need to be added. Also, needs addition of this section - https://github.com/kubernetes/kubernetes-template-project#community-discussion-contribution-and-support to the README. All template files can be found at https://github.com/kubernetes/kubernetes-template-project.

- The following contributors to the repo have not signed the CNCF CLA. As per the [rules](https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#rules-for-donated-repositories), we'll need to wait for sometime (we've at least waited 2 weeks in the past) for contributors to sign the CLA. If there are still contributors who haven't signed the CLA, we'll need to add  NOTICE file to the repo.
Note - we have not added such a NOTICE file to any of the migrated k8s repos until now so it would be nice if we get all contributors to sign the CLA. :grimacing: 

  - @john-delivuk 
  - @rrtaylor 
  - @sergii-koshel-exa
  - @vainu-arto
  - @thisisamurray
  - @skozlov
  - @rjackson90
  - @parsifal-47
  - @nirrozenbaum
  - @montenegrodr
  - @duane-ibm
  - @Multiply

**Note**: if your name is listed above, could you please sign the CNCF CLA so that we can migrate the [k8s-prometheus-adapter](https://github.com/DirectXMan12/k8s-prometheus-adapter) repo to Kubernetes? Instructions on how to sign the CLA can be found [here](https://github.com/kubernetes/community/blob/master/CLA.md). Thank you! :)

**Comment by Multiply** [comment] 2020-09-14 09:30
I've signed it now. Not sure why it wasn't signed, since I've been through that before.

**Comment by s-urbaniak** [comment] 2020-09-15 09:52
@nikhita thank you! If there is anything technical I can help in moving the repository, please let me know too :-)

**Comment by brancz** [comment] 2020-09-15 13:52
@s-urbaniak maybe you can take care of the files that need to be changed/added?

**Comment by rjackson90** [comment] 2020-09-15 14:52
Thanks for the mention, I'd hate to slow this migration. I had previously signed the CLA, but I guess some of my linux foundation account details were out of date. I believe everything's in order now, please let me know if there is further action I need to take.

**Comment by parsifal-47** [comment] 2020-09-15 16:34
Is it supposed to be signed from exactly the same email that I have in commit messages or same github id is enough?

**Comment by s-urbaniak** [comment] 2020-09-15 18:51
@brancz will do :+1:

**Comment by s-urbaniak** [comment] 2020-09-17 09:46
@nikhita question: @lilic expressed interest in co-maintaining prometheus-adapter. I added her OWNER files in https://github.com/DirectXMan12/k8s-prometheus-adapter/pull/314, is that ok from your perspective?

**Comment by DirectXMan12** [comment] 2020-09-21 22:45
I've invited @mrbobbytables as a collaborator in the meantime, so you should be all set from my end.

**Comment by mrbobbytables** [comment] 2020-09-21 23:04
> @nikhita question: @lilic expressed interest in co-maintaining prometheus-adapter. I added her OWNER files in [DirectXMan12/k8s-prometheus-adapter#314](https://github.com/DirectXMan12/k8s-prometheus-adapter/pull/314), is that ok from your perspective?

That should be fine, they will just need to be added as a member to k-sigs before migration, but as a kubernetes org member that won't be an issue 👍

**Comment by nikhita** [comment] 2020-09-22 03:34
> I've invited @mrbobbytables as a collaborator in the meantime, so you should be all set from my end.

GitHub didn't allow adding admin collaborators iirc, not sure if that's changed recently.

We'll need to move the repo to a dummy org first before transferring it to k-sigs. @DirectXMan12 I've invited you to https://github.com/kubernetes-purgatory. When the repo is ready to be migrated i.e. either me or @mrbobbytables has confirmed that the CLA issue is good to go, please transfer the repo to kubernetes-purgatory and we'll get it moved over to kubernetes-sigs. :)

**Comment by vainu-arto** [comment] 2020-09-22 07:25
This should now finally be OK on my side, sorry about the delay (my Github account was deleted and later re-created, which made it fairly difficult to get the LF CLA system and Github back into sync).

**Comment by nirrozenbaum** [comment] 2020-09-25 14:17
Hi, I've signed it using corporate CLA (working at IBM)

**Comment by mrbobbytables** [comment] 2020-09-29 13:34
> Is it supposed to be signed from exactly the same email that I have in commit messages or same github id is enough?

Sorry @parsifal-47 didn't see your question earlier >_< It's tied to the email address with the commit. In the past we've sometimes had to re-add the commits signed by the author with a new email address associated with a valid CLA.

**Comment by parsifal-47** [comment] 2020-09-29 18:50
@mrbobbytables 
done, should be the same email that I used when contributing, thanks!

**Comment by montenegrodr** [comment] 2020-09-29 20:50
I've signed I guess two weeks ago. Did you get that?

**Comment by s-urbaniak** [comment] 2020-11-04 08:50
@nikhita small question, can I help with the following ?
> We'll need to move the repo to a dummy org first before transferring it to k-sigs. @DirectXMan12 I've invited you to https://github.com/kubernetes-purgatory. When the repo is ready to be migrated i.e. either me or @mrbobbytables has confirmed that the CLA issue is good to go, please transfer the repo to kubernetes-purgatory and we'll get it moved over to kubernetes-sigs. :)

**Comment by mrbobbytables** [comment] 2020-11-04 10:28
@s-urbaniak I think we're still waiting on people to finish signing the cla =\ It's been a little bit since I checked, but going from the comments in this thread these folk still need to sign:
@john-delivuk
@rrtaylor
@sergii-koshel-exa
@thisisamurray
@skozlov
@rjackson90
@duane-ibm

**Comment by sergii-koshel-exa** [comment] 2020-11-04 10:32
I've signed already

**Comment by lilic** [comment] 2020-11-04 11:07
@mrbobbytables according to [this comment](https://github.com/kubernetes/org/issues/2182#issuecomment-691877843) it's been longer than the two weeks, if folks don't sign by end of this week would it be okay to just proceed or is there anything else we could do to speed up the process? Thanks!

**Comment by nikhita** [comment] 2020-11-04 14:19
@swinslow @caniszczyk can you please take a look at this from a legal perspective? We want to migrate a repo but there are some contributors who have not signed the CLA. It's been over a month that we have not heard from them.

**Comment by swinslow** [comment] 2020-11-04 15:34
@nikhita Looking through the contributions from this list of folks who haven't signed, it looks like @john-delivuk in particular made several commits that were substantive. I would encourage continuing to try to get @john-delivuk to sign the CLA if possible.

If that fails, then I think the process would be what you linked to in the [rules](https://github.com/kubernetes/community/blob/master/github-management/kubernetes-repositories.md#rules-for-donated-repositories), to add the NOTICE file explicitly stating the situation.

For the others on the list, looking through their commits it looks like they were all extremely minor edits (typo fixes). Although I'd guess many of these are likely to not consist of copyrightable content, I would suggest that if these contributors cannot be reached, that their edits be reverted before it comes over. That way it's clearer that the incoming repo's main branch tip does not contain their content, regardless of the earlier commit history.

**Comment by s-urbaniak** [comment] 2020-11-05 07:49
thank you everyone for the help and instructions how to proceed! :bow: I will try to contact contributors wherever their email is available from their profile.

**Comment by skozlov** [comment] 2020-11-11 05:21
I've signed the CLA.

**Comment by s-urbaniak** [comment] 2020-11-11 08:23
just a small heads-up: unfortunately I cannot reach @duane-ibm @john-delivuk @rjackson90. Those emails have been public on github, but I didn't get any answers so far :man_shrugging:

**Comment by rjackson90** [comment] 2020-11-11 20:23
Hi there! I signed the CLA months ago and must have missed @s-urbaniak 's email. I just fixed a typo, if reverting that commit is the easiest way forward it's fine with me. I've turned on notifications for this thread again so if there's something else that I need to do please let me know.

**Comment by nikhita** [comment] 2020-12-08 04:51
@s-urbaniak :wave: just following up to check if you've received any responses about signing the CLA?

If not, I think we should move ahead with adding a `NOTICE` file explicitly stating the situation. The repo has been ready to be migrated for a while, so I'm hoping we can at least get this in by the end of 2020. :smile: 

fyi @dims

**Comment by s-urbaniak** [comment] 2020-12-09 16:05
@nikhita unfortunately no additional news from my side, I tried to ping, but no additional answers so far :man_shrugging: I would then say let's add the `NOTICE` file :blush:

**Comment by s-urbaniak** [comment] 2021-01-21 15:54
https://github.com/DirectXMan12/k8s-prometheus-adapter/pull/359 was merged with the necessary NOTICE changes. Any advise how to proceed? :)

**Comment by mrbobbytables** [comment] 2021-01-29 13:33
With that I think its now mostly coordinating the migration

**Comment by nikhita** [comment] 2021-01-29 13:42
GitHub doesn't allow migrating user-owned repos, only org-owned repos are allowed. @DirectXMan12 can you transfer the repo to https://github.com/kubernetes-purgatory? You should have an invite to the org.

Once the repo is transferred, we can migrate that to k-sigs.

**Comment by DirectXMan12** [comment] 2021-01-29 19:43
Transfer under way!

**Comment by nikhita** [comment] 2021-01-30 05:40
Repo has been finally migrated! :tada: :rocket: :partying_face: 

New repo location - https://github.com/kubernetes-sigs/prometheus-adapter

Updates:
- I have pushed commits directly to the master branch of prometheus-adapter to fix the filenames for `OWNERS`, `OWNERS_ALIASES` and `SECURITY_CONTACTS`. Before this commit, they all had the `.txt` file extension. If the file extension is incorrect, prow will not be able to recognize the file and you won't be able to approve PRs.
- Updated the repo name from `k8s-prometheus-adapter` to `prometheus-adapter` as requested in the issue body.
- Created https://github.com/kubernetes/org/pull/2476 to add GitHub teams to grant access.
- Created https://github.com/kubernetes/community/pull/5447 to add the repo to sigs.yaml in k/community.

Once https://github.com/kubernetes/org/pull/2476 and https://github.com/kubernetes/community/pull/5447 merge, we can close this issue.

**Comment by s-urbaniak** [comment] 2021-02-01 13:21
thank you @nikhita @brancz @DirectXMan12 :raised_hands: :tada: cc @dgrisonnet

**Comment by nikhita** [comment] 2021-02-01 14:53
All PRs have merged. Closing! :rocket:

**Closed by nikhita** 2021-02-01 14:53 UTC
Labels: area/github-repo, sig/instrumentation
